# -*- coding: utf-8 -*-
"""W4D2_Imbalanced_Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tr2ia0EWHmxtJ0t_DQ24gzwo1jpgWtIc
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

x,y= make_classification(
    n_samples=1000,
    n_features=5,
    weights=[0.95,0.05],
    random_state=42,
)
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
print(pd.Series(y_train).value_counts())

model_1=LogisticRegression()
model_1.fit(x_train,y_train)
y_pred=model_1.predict(x_test)
acc=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
cr=classification_report(y_test,y_pred)
print("acc_model_1 :" , acc)
print("cm_model_1 :" , cm)
print("cr_model_1 :" , cr)


model_2=LogisticRegression(class_weight='balanced')
model_2.fit(x_train,y_train)
y_pred_model_2=model_2.predict(x_test)
acc=accuracy_score(y_test,y_pred_model_2)
cm=confusion_matrix(y_test,y_pred_model_2)
cr=classification_report(y_test,y_pred_model_2)
print("acc_model_2 :" , acc)
print("cm_model_2:" , cm)
print("cr_model_2 :" , cr)


# 1. قبل التعديل (Baseline Model): الأكيويرسي كانت خدّاعة (95%)، والـ Recall للفئة النادرة كان ضعيف جداً (18%) وكان الموديل بيرفض يكتشفها.
# 2. بعد إضافة class_weight='balanced': ارتفع الـ Recall للفئة النادرة بشكل كبير ليصل إلى 73% وقدر الموديل يكتشف أصل أغلب الحالات النادرة.