# -*- coding: utf-8 -*-
"""W4D3_Cross_Validation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192rIdYkjsIbG2s_rkv_4r31JRN9yeACa
"""

import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

x,y=make_classification(
    n_samples =1000,
    n_features=10,
    weights=[0.8, 0.2],
    random_state=42
)
CV = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

model_LogisticRegression=LogisticRegression()
model_DecisionTreeClassifier=DecisionTreeClassifier(random_state=42)

scores_log = cross_val_score(model_LogisticRegression, x, y, cv=CV)
scores_tree = cross_val_score(model_DecisionTreeClassifier, x, y, cv=CV)

print("Logistic Regression")
print("Scores for 5 folds:", scores_log)
print("Mean Accuracy:", scores_log.mean())
print("Standard Deviation:", scores_log.std())
print("#" *90)
print(" Decision Tree ")
print("Scores for 5 folds:", scores_tree)
print("Mean Accuracy:", scores_tree.mean())
print("Standard Deviation:", scores_tree.std())